<?php
return [
    'line1'=>'"AYURVEDA" is made up of two words-Ayuh and Veda. Ayuh means life and Veda means knowledge or science. Thus "AYURVEDA’ in totality means ‘Science of life’. It incorporates all aspects of life whether physical, psychological, spiritual or social.
     What is beneficial and what is harmful to life, what is happy life and what is sorrowful life; all these four questions and life span allied issues are elaborately and emphatically discussed in Ayurveda. It believes the existence of soul before birth and after death too.',
    'line2'=>'Ayurveda, the ancient most health care system originated with the origin of universe. With the inception of human life on earth Ayurveda started being applied. The antique vedic texts have scattered references of Ayurvedic Remedies and allied aspects of medicine and health. Atharva-veda mainly deals with extensive Ayurvedic information.
     That is why Ayurveda is said to be the off shoot of Atharva Veda.',
     'que1'=>'What is the Ayurvedic viewpoint of structure and functions of body?',
     'ans1'=>'Universe as well as human body are made up of five basic elements collectively called ‘Panch Mahabhootas’. These are Aakash (Ether), Vayu (Air), Agni(Fire), Aapa (Water) and Prithvi (Earth). The sixth mandatory component of life is Atma (life spirit) without which life ceases. The human body is made up of Doshas (Bio-humours), Dhatus(Body matrix) and Malas (excretable products). Vata, Pitta and kapha, known as Tridoshs are physiological entities of the body which are responsible for carrying out all the functions of the body. Dhatus are the structural entities of the body. These are Rasa (Plasma), Rakta (Blood cells), Mamsa (Muscular tissue), Meda (Fatty tissue), Asthi (Bony tissue), Majja (Bone marrow) and Shukra (Hormonal and other secretions of genital). Agni (Metabolic fire) is in thirteen different forms and carries out the whole metabolism of the body. The waste products of the body which are excretable are produced in the body as bye-products of metabolism. These are known as malas which include pureesh (faeces), Sweda (sweat) and Mutra (urine).
      All bio-transformations within the body occur through Srotases (body channels) which are the sites for action of agni.',
     'que2'=>'How is diagnosis done in Ayurveda?',
     'ans2'=>'Diagnostic procedures in Ayurveda are two pronged; one is aimed to establish the state and type of pathology and second to decide the mode of treatment tobe applied. The former implies examination of the patient and make different investigations to diagnose the disease entity. Inspection, palpation, percussion and interrogation are the main modes of physical examination. The second type of examination is to assess the strength and physical status of the individual so that accordingly the type of management required could be planned. For this examination of Prakriti (Body constitution), Saar (Tissue quality), Samhnan (physique), Satva (Mental strength), Satamya (specific adaptability), Aaharshakti (diet intake capacity), Vyayaam shakti (exercise capacity) and Vaya (age) is done.
      On the basis of this examination the individual is decided to be having Pravar bal (excellent strength), Madhyam Bal (moderate strength) or Heen Bal (low strength).',
     'que3'=>'What are the modes of Ayurvedic treatment?',
     'ans3.1'=>'There exists eight divisions of Ayurvedic therapeutics, namely Kayachikitsa (Internal medicine), Shalya (Surgery), Shalkya (Otorhinolaryngology and Opthalmology), Kaumr Bhritya (Paediatrics, Gynaecology and Obstetrics) Agad tantra (Toxicology), Rasayana (Gerentorology), Vajikaran (Aphrodisiacs) and Bhoot Vidya (Psychiatry).',
     'ans3.2'=>'The principles of treatment are Shodhan (purificatory), Shaman (palliative and conservative), Nidan parivarjan (avoidance of causative and prescipitating factors of disease) and Pathya Vyavastha (do’s and don’ts regarding diets lifestyle). Shodhan therapy includes Vamana (medically induced emesis), Virechana (medically induced laxation), Vasti (medicated enema), shirovirechana (administration of medicines through nose) and Raktmokshan (bloodletting). These therapeutic procedures are collectively known as Panchkarma. Before executing Panch karma treatment Snehan (olation) and Swedan (getting perspiration) are to employed first.',
     'que4'=>'What are the main classical reference books of Ayurveda?',
     'ans4'=>'The main classical texts for reference of Ayurvedic principles comprise of Charak Samhita, Susrut Samhita, Astang Hridaya, Sharangdhar Samhita, Madhav Nidan, Kashyap Samhita, Bhavprakash and Bhaisajya Ratnavali etc.',
     'que5'=>'
     Is there scope for Ayurveda in the contemporary period?',
     'ans5'=>'Ayurveda has a wide scope as far as the prevention of disease, promotion of health and its preservation are concerned. Lifestyle rules mentioned in Ayurvedic texts if applied rigorously give definite results. Lifestyle related diseases, drug abuse, degenerative diseases, auto immune diseases and certain metabolic and allergic disorders are well manageable with Ayurvedic techniques and medicaments.',
     'que6'=>'Is Ayurveda recognized by W.H.O?',
     'ans6'=>'About 20 years back, W.H.O. adopted Traditional Medicine programme in conjunction with the goal of health for all with the adoption of primary health care approach. W.H.O. has an open mind on Traditional Medicine. However, it endorses only that therapy which has solid scientific evidence with no toxicity. In view of this Ayurveda is duly recognized by W.H.O.',
     'que7'=>'Does Ayurvedic system of medicine have plus points over conventional medicinal system?',
     'ans7'=>'Being holistic and disease eradicative with principles of individualised treatment, condusive to socio-economic conditions of India and with availability of abundance of formulations for any particular disease, use of food items as medicine and lifestyle rules, Ayurveda enjoys a better place in respect of prevention and cure of the disease is concerned in comparison to western medical system.',
     'que8'=>'What is regulatory mechanism for Ayurvedic education and practice in India?',
     'ans8.1'=>'The Central Council of Indian Medicine is a body corporate established under the provisions of IMCC Act, 1970 to maintain Central Register of Practitioners of Indian Medicines and for dealing with matters connected therewith. The Council is responsible for maintaining the minimum standards of education. This Council as per the provisions in the Act. Introduced the following courses through Regulations. ',
     'ans8.2'=>'•	Ayurveda Degree Course -- Ayurvedacharya (BAMS)',
     'ans8.3'=>'•	Ayurveda Post GraduateDegree Course -- Ayurved Vachaspati (MD Ayurved)',
     'ans8.4'=>'•	Ayurved Varidhi -- Ph.D Ayurveda',
     'que9'=>'How safe is to buy Ayurveda Medicines over the counter?',
     'ans9'=>'Medicines are safe if the manufacturer is licensed and the label of the container specifically describes date of manufacturing, expiry date, batch number of the medicine, dose and indications along with ingredients of the medicine and necessary precaution.',
     'que10'=>'What are the main Rasayana (Immuno-modular) Medicines of Ayurveda?',
     'ans10.1'=>'Ashavgandha (Withania somnifera), Guduchi (Tinospora cordifolia), Amla (Emblica officinalis), Haritaki (Terminalia chebula), Shilajeet (Black bitumen or Mineral pitch), Suvarn Bhasm (incinerated Gold with herbal excipients) are very potent Rasayana medicines, prescribed judiciously in somatic degenerative disease conditions for immuno-modulation and and adaptogenic effects.
      Mandookparni (Bacopa Monieri), Mulethi (Glycirrhiza glabra), Guduchi (Tinospora cordifolia) and Shankhapushpi (Convolvulus Plenricaulis) are from main Psychomodular Rasayanas used extensively in mental disorders and for improving higher mental functions like concentration, retention and memory, Vijaysara (Pterocaspus marsupium) for Diabetes Mellitus, Katuka (Picrosshiza kurco) for liver disorders Vidang (Abies Webiana) for Hoelminthic induced Gasto intestinal problem, Bakuchi (Psorylia Corylifolia) for Leucoderma Bhallatak (Semecarpur anacardium) for piles and autoimmune disorders), Shirees (Albizzia Lebek) fr allergic conditions), Vacha (Acorus clamus) for speech disorders, haldi (Curcuma Longa) for urinary, allergic and septic problems, Neem (Melia Azadiracta) and Khadir (Acacia Catechu) for skin problems and Chirayata (swertia chirayata) for febrile disorders are some of the other Rasayana Medicines for disease-wise use.',
     'ans10.2'=>'Apart from the above mentioned medicines there is an eleborate code of conduct described in the classical text for achieving rejuvenation and maintaining youthfulness.',
     'que11'=>'What are the common Ayurveda Medicines which can be used without consulting the doctors?',
     'ans11'=>'Simple herbal medicines like powders, pills & tablets , syrups and decoctions can be used for the management of common ailments like cough, cold, fever, indigestion, vomiting, diarrhea, loss of appetite, body & joint pains etc, even without the prescription of a doctor. Similarly, herbal tonics/ health foods can also be consumed if the same do not create any alarming discomfort or upsets.',
     'que12'=>'What are the aphrodisiacs/Sexual Tonics for improving the quality of semen/sperm count and motility and fertility?',
     'ans12'=>'Musli, Kaunch, Shatavari, Gokshur, Ashavgandha, Utangan, Salmpanja, Vidari, Vijaya, urd, Bhautak, Akarkara, Abhrak Bhasm, trivang Bhasm, Makardhvaj are some of the Vajikarana medicines which on judicious use and adoption or specific do’s and don’ts of diet, definitely give a desired result.',
     'que13'=>'What is Herbal Tea?',
     'ans13'=>'Herbal tea is a misnomer, which confuses the consumer that it is a sort of tea made of tea leaves and other herbal ingredients. Actually, Herbal Tea is a combination of certain medicinal herb components devoid of tea leaves, which on boiling gives a palatable decoction and can be used as an alternative to conventional tea. In accordance to the composition the so called herbal tea has appetizing, antacid, soothing, antitussive, anti common cold and anti pyretic effects.',
];
